import { GoogleGenerativeAI } from "@google/generative-ai";
import dotenv from "dotenv";
dotenv.config();

// --- 1. CONFIG & INITIALIZATION ---
const API_KEY = process.env.GEMINI_API_KEY;

// --- MODEL NAME (Using the one that works) ---
const DEFAULT_MODEL = "gemini-2.5-flash"; // Yeh model 100% chalega
// const DEFAULT_MODEL = "gemini-2.5-flash"; // Yeh 404 error de raha tha

if (!API_KEY || API_KEY.length < 10) {
  console.error("❌ FATAL: Google Gemini API Key not found or invalid. Please check .env");
}

const genAI = new GoogleGenerativeAI(API_KEY);

class AIService {
  constructor() {
    this.model = genAI.getGenerativeModel({ model: DEFAULT_MODEL });
    console.log(`✅ AIService (Gemini) initialized with model: ${DEFAULT_MODEL}`);
  }

  // --- 2. METHODS ---

  /**
   * FEATURE 1: Description
   * (Ismein koi badlav nahi)
   */
  async generateDescription(propertyData) {
    const prompt = this._buildDescriptionPrompt(propertyData);
    console.log("🧠 AIService: Generating property description...");
    
    try {
      const result = await this.model.generateContent(prompt);
      const response = await result.response;
      const generatedText = response.text().trim();
      if (!generatedText || generatedText.length < 50) {
        throw new Error("AI returned an empty or blocked description.");
      }
      console.log("✅ AIService: Description generated successfully.");
      return generatedText;
    } catch (error) {
      console.error("❌ Gemini API Error (generateDescription):", error);
      throw new Error(`Failed to generate description: ${error.message}`);
    }
  }

  /**
   * FEATURE 2: Investment Insights
   * (Logs already added, logic is correct)
   */
  async generateInvestmentInsights(investmentData, marketTrends = null) {
    // Ab prompt builder ko market data bhi bhejien
    const prompt = this._buildInvestmentPrompt(investmentData, marketTrends);
    console.log("🧠 AIService: Generating SUPERCHARGED investment insights (requesting JSON)...");

    try {
      const result = await this.model.generateContent(prompt);
      const response = await result.response;
      
      // AI se text lein aur usse JSON mein badlein
      let jsonText = response.text().trim();
      
      // AI kabhi-kabhi ```json tag laga deta hai, usse saaf karein
      if (jsonText.startsWith("```json")) {
        jsonText = jsonText.substring(7, jsonText.length - 3).trim();
      }

      console.log("Raw JSON text from AI:", jsonText);
      
      // Text ko JSON object mein parse karein
      const generatedJson = JSON.parse(jsonText);

      if (!generatedJson || !generatedJson.priceAnalysis) { // Check karein ki JSON valid hai
        throw new Error("AI returned invalid JSON structure.");
      }
      
      console.log("✅ [aiService] ---- STEP 3b: Investment JSON generated by Gemini successfully. ----");
      return generatedJson; // JSON object return karein

    } catch (error) {
      console.error("❌ [aiService] Gemini API Error (generateInvestmentInsights):", error);
      // Agar JSON.parse fail hota hai toh woh error bhi yahan pakda jayega
      throw new Error(`Failed to generate insights: ${error.message}`);
    }
  }

  /**
   * FEATURE 3: Listings Summary
   * (Ismein koi badlav nahi)
   */
  async analyzeProperties(properties, searchCriteria) {
    console.log("🧠 AIService: Analyzing property list summary...");
    const preparedProperties = this._preparePropertyData(properties);
    const prompt = `You are a helpful real estate expert. Based *only* on the following properties found in our database, provide a concise analysis for a user searching for a ${searchCriteria.type} in ${searchCriteria.city}.

      SEARCH CRITERIA: ${JSON.stringify(searchCriteria)}
      PROPERTIES FOUND: ${JSON.stringify(preparedProperties, null, 2)}

      INSTRUCTIONS:
      1.  **Quick Summary:** A one-paragraph overview of the properties.
      2.  **Best Value:** Which property seems to offer the best value?
      3.  **Top Pick:** Based on the data, which property would you recommend?
      Keep your response concise and under 200 words.
      `;
    
    try {
      const result = await this.model.generateContent(prompt);
      const response = await result.response;
      console.log("✅ AIService: Property summary generated.");
      return response.text();
    } catch (error) {
      console.error("❌ Gemini API Error (analyzeProperties):", error);
      throw new Error(`Failed to analyze properties: ${error.message}`);
    }
  }

  /**
   * FEATURE 4: Location Trends Analysis
   * (Ismein koi badlav nahi)
   */
  async analyzeLocationTrends(scrapedTrends, city) {
    console.log("🧠 AIService: Analyzing scraped location trends...");
    const prompt = `You are a real estate expert. I have scraped the following *live* price trends data for localities in ${city}.

      SCRAPED DATA: ${JSON.stringify(scrapedTrends, null, 2)}

      INSTRUCTIONS:
      Based *only* on this scraped data, provide a brief analysis:
      1.  **Market Overview:** A quick summary of the price trends.
      2.  **Top Localities:** Which localities seem most expensive?
      3.  **Investment Insight:** A single quick tip based on this data.
      Keep your response concise and under 150 words.
      `;

    try {
      const result = await this.model.generateContent(prompt);
      const response = await result.response;
      console.log("✅ AIService: Location trends analyzed.");
      return response.text();
    } catch (error) {
      console.error("❌ Gemini API Error (analyzeLocationTrends):", error);
      throw new Error(`Failed to analyze location trends: ${error.message}`);
    }
  }


  // --- 3. PRIVATE HELPER METHODS ---

  /**
   * Helper: Description Prompt
   * (Ismein koi badlav nahi)
   */
  _buildDescriptionPrompt(data) {
    let { title, price, type, bedroom, bathroom, address, details } = data;
    if (typeof details === "object") {
 	    try { details = JSON.stringify(details, null, 2); } catch { details = "N/A"; }
 	  }
    const tones = ["friendly and professional", "warm and conversational", "modern and realistic"];
    const audiences = ["young professionals", "small families", "students", "couples"];
    const tone = tones[Math.floor(Math.random() * tones.length)];
    const audience = audiences[Math.floor(Math.random() * audiences.length)];
    const chosenPrompt = `Write a real estate property description that feels ${tone}, for ${audience}. Focus on real-world appeal.`;

    return `
${chosenPrompt}
Details:
🏠 Title: ${title || "N/A"}
💰 Price: ₹${price || "N/A"}
📍 Address: ${address || "N/A"}
🏡 Type: ${type || "N/A"}
🛏️ Bedrooms: ${bedroom || "N/A"}
🛁 Bathrooms: ${bathroom || "N/A"}
📋 Additional Details: ${details || "N/A"}

Guidelines:
1. Keep tone ${tone}.
2. Mention nearby amenities, safety, and neighborhood vibe.
3. Keep it concise (100–150 words).
4. Output only the paragraph description.
`;
  }

  /**
   * Helper: Investment Prompt
   * (Logs already added, logic is correct)
   */
  _buildInvestmentPrompt(data, marketTrends = null) {
    const { title, price, type, address, size, goal, city } = data;
    const priceFormatted = price ? Number(price).toLocaleString() : "N/A";
    const sizeDisplay = size ? `${size} sqft` : "N/A";

    let marketContextPrompt = "No live market data available for comparison.";
    if (marketTrends && marketTrends.length > 0) {
        marketContextPrompt = `
Here is the LIVE scraped price trend data for ${city}:
${JSON.stringify(marketTrends, null, 2)}
        `;
        console.log(`[aiService Prompt Helper] Market context added to prompt for city: ${city}`);
    } else {
        console.log(`[aiService Prompt Helper] No market context added to prompt.`);
    }

    // --- NAYI INSTRUCTIONS (JSON FORMAT) ---
    return `
You are an experienced real estate investment analyst in India. Analyze the property below.

---
PROPERTY DETAILS:
- Title: ${title}
- Price: ₹${priceFormatted}
- Type: ${type}
- Location: ${address} (City: ${city})
- Size: ${sizeDisplay}
- Investment Goal: ₹${Number(goal).toLocaleString()}
---
LIVE MARKET CONTEXT (from scraping):
${marketContextPrompt}
---

INSTRUCTIONS:
Analyze the property and the market context.
**Respond ONLY with a valid JSON object** in the following format. Do NOT add any text, markdown (like \`\`\`json), or explanation before or after the JSON object.

Your JSON output format MUST be:
{
  "priceAnalysis": {
    "verdict": "e.g., Underpriced, Overvalued, Fairly Priced, or Suspicious",
    "reasoning": "e.g., This property is priced at ₹X/sqft, while the market average for similar localities like [Scraped Locality] is ₹Y/sqft, making it significantly underpriced."
  },
  "marketTrend": {
    "direction": "Analyze the 'priceChange' data (e.g., '81.1% in 5Y' = Up, 'N/A' = Stable, '-10% in 1Y' = Down). Output 'Up', 'Down', or 'Stable'.", 
    "changeText": "e.g., 'Avg. 81.1% in 5Y' (Pick the most relevant 'priceChange' value from the scraped data, or 'N/A' if none exists)",
    "insight": "e.g., The local market is showing strong appreciation, indicating good growth potential."
  },
  "investmentStrategy": {
    "recommendation": "e.g., Buy & Hold, Flip, or Avoid",
    "reasoning": "e.g., Given the high growth and good rental yield, a Buy & Hold strategy is recommended to maximize returns towards your goal."
  },
  "keyRisk": {
    "title": "e.g., High Fraud Risk",
    "details": "e.g., The price is unrealistically low compared to market data, suggesting it might be a scam or have legal issues."
  },
  "keyOpportunity": {
    "title": "e.g., High Growth Area",
    "details": "e.g., This property is in an emerging area with new infrastructure projects, offering a high potential for long-term value increase."
  }
}
`;
  }

  /**
   * Helper: Prepare Property Data
   * (Ismein koi badlav nahi)
   */
  _preparePropertyData(properties) {
    return properties.map(property => ({
      title: property.title,
      type: property.type,
      city: property.city,
      price: property.price,
      bedroom: property.bedroom,
      description: property.description 
        ? property.description.substring(0, 100) + '...'
        : ''
    }));
  }
}

// Poori class ka ek single instance export karein
export default new AIService();